#!/bin/bash
#SBATCH --job-name=obrobka_sz
#SBATCH -p std-1gpu
#SBATCH --time=0-10:00:00
#sbatch --no-requeue
#SBATCH --output=OUT-sz_%j.txt
#SBATCH --error=ERR-sz_%j.txt

#skrypt wymaga: resultMerger.jar w katalogu wywolania, oraz istnienia katalogu 'merged' (lub inna nazwa) oraz w nim: program + config.txt (odpowiednio ustawiony) [+startArguments.txt] oraz filterCopy.jar + FilterConfig.txt
#UWAGA: potrzeba w katalogu wywołania pliku 'startArguments.txt' - resultMerger patrzy w nim na listę ciśnień, po której ma składać foldery (stworzy po jednym folderze wynikowym dla każdego ciśnienia, zawierającym badania z zadanego przedziału). Program się zawiesi, jeżeli nie znajdzie folderu, z którymkolwiek ciśnieniem (wszystkie, które są w pliku, muszą być obecne w rzeczywistości). V/V_CP w pliku 'startArguments.txt' - jest całkowicie nieważne.

cd $SLURM_SUBMIT_DIR;
source scriptConfig;
listLength=$(wc -l ${startArgumentsFileName} | cut -f1 -d' ');
time srun java -jar resultMerger.jar ${newDirectoryName} ${N} ${gaps} ${G} ${mN} ${mD} ${minDirectory} ${maxDirectory} ${liczbaDanych};
cd ${newDirectoryName};
for ((pointNumberP=0;pointNumberP<${listLength};pointNumberP++)); do
   time srun ./program 5 none ${linesToSkip} ${N} ${gaps} ${mD} ${G} ${startPointNumber} 0 ${useSpecificDir} ${pointNumberP};
done
time srun java -jar filterCopy.jar;

#cd $PBS_O_WORKDIR;
#source scriptConfig;
#listLength=$(wc -l ${startArgumentsFileName} | cut -f1 -d' ');
#time java -jar resultMerger.jar ${newDirectoryName} ${N} ${gaps} ${G} ${mN} ${mD} ${minDirectory} ${maxDirectory} ${liczbaDanych};
#cd ${newDirectoryName};
#for ((pointNumberP=0;pointNumberP<${listLength};pointNumberP++)); do
#   time ./program 5 none ${linesToSkip} ${N} ${gaps} ${mD} ${G} ${startPointNumber} 0 ${useSpecificDir} ${pointNumberP};
#done
#time java -jar filterCopy.jar;


exit 0
