#!/bin/bash
#SBATCH --job-name=obrobka_sz
#SBATCH -p fast
#SBATCH --time=0-01:00:00
#SBATCH --no-requeue
#SBATCH --output=OUT-sz_%j.txt
#SBATCH --error=ERR-sz_%j.txt

#skrypt wymaga: resultMerger.jar w katalogu wywolania, oraz istnienia katalogu 'merged' (lub inna nazwa) oraz w nim: program + config.txt (odpowiednio ustawiony) [+startArguments.txt] oraz filterCopy.jar + FilterConfig.txt
#UWAGA: potrzeba w katalogu wywołania pliku 'startArguments.txt' - resultMerger patrzy w nim na listę ciśnień, po której ma składać foldery (stworzy po jednym folderze wynikowym dla każdego ciśnienia, zawierającym badania z zadanego przedziału). Program się zawiesi, jeżeli nie znajdzie folderu, z którymkolwiek ciśnieniem (wszystkie, które są w pliku, muszą być obecne w rzeczywistości). V/V_CP w pliku 'startArguments.txt' - jest całkowicie nieważne.

cd $SLURM_SUBMIT_DIR;
source scriptConfig;

mD=$(cut -f1 fileStartArguments | head -n ${1} | tail -1);
minPoint=$(cut -f2 fileStartArguments | head -n ${1} | tail -1);
maxPoint=$(cut -f3 fileStartArguments | head -n ${1} | tail -1);
additionalMinIndex=$(cut -f4 fileStartArguments | head -n ${1} | tail -1);
additionalMaxIndex=$((${additionalMinIndex} + 1));

listLength=$(wc -l ${startArgumentsFileName} | cut -f1 -d' ');
time srun java -jar resultMerger.jar ${newDirectoryName} ${N} ${gaps} ${G} ${mN} ${mD} ${minDirectory} ${maxDirectory} ${additionalMinIndex} ${additionalMaxIndex} ${liczbaDanych};
cd ${newDirectoryName};
for ((pointNumberP=${additionalMinIndex};pointNumberP<${additionalMaxIndex};pointNumberP++)); do
   time srun ./program 5 none ${linesToSkip} ${N} ${gaps} ${mD} ${G} ${minPoint} $((${maxPoint}-${minPoint})) ${useSpecificDir} ${pointNumberP};
done
#time srun java -jar filterCopy.jar;

#cd $PBS_O_WORKDIR;
#source scriptConfig;
#listLength=$(wc -l ${startArgumentsFileName} | cut -f1 -d' ');
#time java -jar resultMerger.jar ${newDirectoryName} ${N} ${gaps} ${G} ${mN} ${mD} ${minDirectory} ${maxDirectory} ${liczbaDanych};
#cd ${newDirectoryName};
#for ((pointNumberP=0;pointNumberP<${listLength};pointNumberP++)); do
#   time ./program 5 none ${linesToSkip} ${N} ${gaps} ${mD} ${G} ${startPointNumber} $((${maxPoint}-${startPointNumber})) ${useSpecificDir} ${pointNumberP};
#done
#time java -jar filterCopy.jar;


exit 0
